"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { signInWithEmail, signInWithGoogle } from "@/lib/firebase/auth";
import { loginSchema, LoginFormData } from "@/lib/utils/validators";
import { useToast } from "@/context/ToastProvider";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";

export function LoginForm() {
  const router = useRouter();
    const searchParams = useSearchParams();
      const { error: showError } = useToast();
        const [loading, setLoading] = useState(false);
          const [googleLoading, setGoogleLoading] = useState(false);
          
            const {
                register,
                    handleSubmit,
                        formState: { errors },
                          } = useForm<LoginFormData>({
                              resolver: zodResolver(loginSchema),
                                });
                                
                                  const getRedirectUrl = () => {
                                      const redirectParam = searchParams.get("redirect");
                                          if (!redirectParam) return "/";
                                              try {
                                                    const parsed = JSON.parse(decodeURIComponent(redirectParam));
                                                          if (parsed?.name === "offer-new" && parsed?.params?.type) {
                                                                  return `/offer/new/${parsed.params.type}`;
                                                                        }
                                                                              if (parsed?.path) return parsed.path;
                                                                                  } catch {
                                                                                        return redirectParam;
                                                                                            }
                                                                                                return "/";
                                                                                                  };
                                                                                                  
                                                                                                    const onSubmit = async (data: LoginFormData) => {
                                                                                                        setLoading(true);
                                                                                                            try {
                                                                                                                  await signInWithEmail(data.email, data.password);
                                                                                                                        router.push(getRedirectUrl());
                                                                                                                            } catch (err: unknown) {
                                                                                                                                  const message = err instanceof Error ? err.message : "Failed to sign in";
                                                                                                                                        showError(message);
                                                                                                                                            } finally {
                                                                                                                                                  setLoading(false);
                                                                                                                                                      }
                                                                                                                                                        };
                                                                                                                                                        
                                                                                                                                                          const handleGoogleSignIn = async () => {
                                                                                                                                                              setGoogleLoading(true);
                                                                                                                                                                  try {
                                                                                                                                                                        await signInWithGoogle();
                                                                                                                                                                              router.push(getRedirectUrl());
                                                                                                                                                                                  } catch (err: unknown) {
                                                                                                                                                                                        const message = err instanceof Error ? err.message : "Failed to sign in with Google";
                                                                                                                                                                                              showError(message);
                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                        setGoogleLoading(false);
                                                                                                                                                                                                            }
                                                                                                                                                                                                              };
                                                                                                                                                                                                              
                                                                                                                                                                                                                return (
                                                                                                                                                                                                                    <Card className="w-full max-w-md mx-auto">
                                                                                                                                                                                                                          <CardHeader>
                                                                                                                                                                                                                                  <CardTitle>Welcome back</CardTitle>
                                                                                                                                                                                                                                          <CardDescription>Sign in to your account to continue</CardDescription>
                                                                                                                                                                                                                                                </CardHeader>
                                                                                                                                                                                                                                                      <CardContent>
                                                                                                                                                                                                                                                              <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
                                                                                                                                                                                                                                                                        <Input
                                                                                                                                                                                                                                                                                    label="Email"
                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                            placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                                        error={errors.email?.message}
                                                                                                                                                                                                                                                                                                                                    {...register("email")}
                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                        <Input
                                                                                                                                                                                                                                                                                                                                                                    label="Password"
                                                                                                                                                                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Enter your password"
                                                                                                                                                                                                                                                                                                                                                                                                        error={errors.password?.message}
                                                                                                                                                                                                                                                                                                                                                                                                                    {...register("password")}
                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/forgot-password" className="text-sm text-accent hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Forgot password?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button type="submit" fullWidth loading={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Sign in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="relative my-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="absolute inset-0 flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-full border-t border-border" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="relative flex justify-center text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="px-2 bg-card text-muted">or continue with</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "